### ISSUE TITLE
Using spy on a TS > 4.3.x project causes  CombineLatest ref to be function instead of Observable 

### ISSUE THREAD

**Issue by LironHazan** [TypeStrong/ts-mockito#15]
@pauleustice 

Thinking out load:
With TS 4.4.x following line fails: 
`service.combinedProviderObservable$.subscribe((value)`

TypeError: service.combinedProviderObservable$.subscribe is not a function

I've printed the service for 4.4.x and got:       
`'**combinedProviderObservable$**': [Function (anonymous)],
`

And for 4.3.x  we get:
```
     'combinedProviderObservable$': Observable {
        _isScalar: false,
        source: Observable {
          _isScalar: false,
          source: [Observable],
          operator: [CombineLatestOperator]
        },
        operator: MapOperator { project: [Function (anonymous)], thisArg: undefined }
      }
```

When removing the use of spy it works in 4.4.x,
In TS 4.4.x: When using spy CombineLatest returns a function ref and without the spy the CombineLatest returns an observable.
Won't happen in TS 4.3.x
Wow I don't have a clue, 
I'm unfamiliar as well with the spy related code, but what I can do in this repo is adding the test with rxjs that would fail and then we can debug on ts-mockito source

**Comment by pauleustice** [comment]
For reference, previous discussions relating to this issue can be found starting with [this comment](https://github.com/TypeStrong/ts-mockito/issues/3#issuecomment-1190374393).

**Comment by LironHazan** [comment]
@pauleustice --> 
https://github.com/TypeStrong/ts-mockito/tree/15-combinelatest-as-function-issue/test/issue15
Added the tests, fails for same reason and now we can debug,
I'll try to look into it later on today

**Comment by pauleustice** [comment]
@LironHazan Cool! I've added some logging into `Mock.js` (which `Spy.js` extends).

[Mocker.prototype.processProperties](https://github.com/TypeStrong/ts-mockito/blob/master/src/Mock.ts#L124):

```
if (descriptor.get) {
    console.log('has getter');
    _this.createPropertyStub(name);
    _this.createInstancePropertyDescriptorListener(name, descriptor, obj);
    _this.createInstanceActionListener(name, obj);
}
else if (typeof descriptor.value === "function") {
    console.log('function');
    _this.createMethodStub(name);
    _this.createInstanceActionListener(name, obj);
}
else {
  console.log('neither');
}
```

When it iterates over the class fields on ExampleService, the following happens:

```
  console.log
    observable$

  console.log
    neither
    
  console.log
    providerOneObservable$

  console.log
    neither
    
  console.log
    combinedProviderObservable$

  console.log
    function
```

That's why the stub is being added. Now we need to work out what the difference in TS version is, that means the `combineLatest` Observable is a function.

**Comment by pauleustice** [comment]
@LironHazan I haven't had a chance to do too much more on this, but I've just attempted to isolate the issue further by using ts-mockito outside of Jest. I created a basic TS file, which behaves as expected:

```
import { Observable } from 'rxjs';
import { BehaviorSubject, combineLatest } from 'rxjs';

import { spy } from 'ts-mockito';

class SimpleClass {
  observable$ = new BehaviorSubject('one');
  observableTwo$ = new BehaviorSubject('two');

  localCombinedObservable$: Observable<string[]> = combineLatest([
    this.observable$,
    this.observableTwo$,
  ]);
}

const simple = new SimpleClass();

spy(simple);

simple.localCombinedObservable$.subscribe(([ one, two ]) => {
  console.log(one, two);
});
```

This suggests to me that it isn't Typescript / ts-mockito exclusively, more like Jest, ts-jest or something else... 🤔

**Comment by LironHazan** [comment]
@pauleustice Interesting and a different angle than what I thought, 
I found that MockableFunctionsFinder recognised the following code as a function 

```
        this.localCombinedObservable$ = (0, rxjs_1.combineLatest)([
            this.observable$,
            this.observableTwo$,
        ]).pipe((0, operators_1.map)(function (_a) {
            var first = _a[0], another = _a[1];
            return "".concat(first, "/").concat(another);
        }));
```
This is the transpiled code as string when running version > 4.3.x

And for 4.3.5 its:
```
this.combinedProviderObservable$ = rxjs_1.combineLatest([
   this.providerOne.observable$,
   this.providerTwo.observable$,
]).pipe(operators_1.map(function (_a) {
   var second = _a[0], third = _a[1];
   return second + "/" + third;
}));
```
I tried to fix the "functionNameRegex" but that didn't work, 
But now I don't think that's the issue after seeing your isolated example

**Comment by LironHazan** [comment]
@pauleustice btw I tried running with karma instead and still fails for same reason,
`      TypeError: service.combinedProviderObservable$.subscribe is not a function
`

**Comment by pauleustice** [comment]
Interesting... so it's probably not Jest then! So in your examples above, did MockableFunctionsFinder not show up the `this.localCombinedObservable`? Both of them yield the same result. I probably won't have time to look at this again today but when I next do, I'll look at that regex too.

**Comment by pauleustice** [comment]
Oh wow, amazing work! Let me know if I can help, I can make some time tomorrow!

**Comment by johanblumenberg** [comment]
I fixed it in my fork: https://github.com/johanblumenberg/ts-mockito/commit/08979c2f236580a71592fdb4c1b2f2ad53030cc8

I opened a PR to try to fix it in this repository as well, but it wasn't straightforward. See details in https://github.com/TypeStrong/ts-mockito/pull/17.

**Comment by LironHazan** [comment]
@pauleustice I started to resolve it using a parser https://github.com/TypeStrong/ts-mockito/pull/17#issuecomment-1195156354 but I want to try to merge @johanblumenberg PR instead
