### ISSUE TITLE
[META] fork / upstream maintenance discussion

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-mockito#3]
In NagRock/ts-mockito/issues/212

There is discussion about adding maintainers to the original `ts-mockito` project.

I still hope the author, NagRock, is able to add maintainers.  Barring that, we may want to collaborate on this fork: https://npmjs.com/package/@johanblumenberg/ts-mockito

I also have access to the `@TypeStrong` org, and we can consider moving the project there.

---

Other links:

This fork needs passing tests, being discussed in #2

**Comment by LironHazan** [comment]
All tests are passing now,  the node version on git workflow was updated to v14.15.5 
Future improvements IMO:
- Configure prettier + eslint instead of tslint, we can also 
- Can try to get a better score --> https://snyk.io/advisor/npm-package/ts-mockito seek for vulnerabilities and resolve them, improve the documentation etc..

**Comment by LironHazan** [comment]
Should open a PR for merging [#194](https://github.com/NagRock/ts-mockito/pull/194)
**Fixed problem with a mock resolving a mocked value with Promises** by @jlkeesey
Seems there are 2 discussions around it:
[#191 ](https://github.com/NagRock/ts-mockito/issues/191)
[#219](https://github.com/NagRock/ts-mockito/issues/219)
The PR was approved but never merged
@cspotcode what is the acceptable approach of porting PR's opened for the original repo into the forked repo?
Not sure it's possible to access the [#194 ](https://github.com/NagRock/ts-mockito/pull/194) commits from the forked repo, will just copying and leaving a comment with the issue id near the fix be OK?

**Comment by cspotcode** [comment]
> Not sure it's possible to access the #194 commits from the forked repo, will just copying and leaving a comment with the issue id near the fix be OK?

The pull request creation UI should allow creating a pull request from any branch to any branch.  Once I pick the correct forks and branches in the dropdowns, it appears to show me the correct commits.

![image](https://user-images.githubusercontent.com/376504/134950675-4ab4ae10-3648-4fa2-9b5d-acdd3179f508.png)

**Comment by cspotcode** [comment]
I created PR #5 for this.

**Comment by LironHazan** [comment]
@cspotcode awesome! thanks I'll try doing that myself with another PR

**Comment by LironHazan** [comment]
Ported a **feature** PR [#140](https://github.com/NagRock/ts-mockito/pull/140) **mock free functions**

**Comment by LironHazan** [comment]
Ported [#139](https://github.com/NagRock/ts-mockito/pull/139) **Matcher types**

**Comment by cspotcode** [comment]
I sent a support ticket to npm support requesting a transfer of the @typestrong scope.  If we want, and if they approve the transfer, we can publish ts-mockito under the @typestrong/ts-mockito scope.

**Comment by LironHazan** [comment]
@cspotcode I know I already opened PR's for porting features from @johanblumenberg but come to think of it after reading the latest comments on the [maintenance](https://github.com/NagRock/ts-mockito/issues/212#issuecomment-932696247) thread I realized that maybe it would be better to resolve un-addressed "pains" - issues first and have a clear agenda of how it would be maintained outside of the original repo in case the author wouldn't intend to merge the fork into the original repo, I understand that most of the participants of the thread would like to see the original repo maintained but I have a lack of faith in personal repos in situation like those and IMO a heavily used project should have a community with a clear code of conduct, agenda, skilled developers willing to contribute - saying this carefully, as I do respect the work that was done by the author and others, I just feel the thread is moving in circles..
If I'll see we're making a progress with @typestrong/ts-mockito I'll start using that..

**Comment by cspotcode** [comment]
I like moving to TypeStrong.  Github will let me transfer this repository to TypeStrong today.  Is there more to discuss, or are we ready to do that right now?

**Comment by LironHazan** [comment]
@cspotcode Let's rock \m/

**Comment by cspotcode** [comment]
Transfer complete.  You should still have full access.  If the permissions got dropped for some reason, let me know and I'll be sure to fix it.

**Comment by LironHazan** [comment]
@cspotcode cool I see I have access, I'll try to find the time to replace tslint in eslint after my working hours and maybe go over the issues see if there's some bugs that still happen that can be resolved. LMK when you'll publish to npm, worth adding a badge to the readme.

**Comment by cspotcode** [comment]
@LironHazan where do you want to publish in the short-term?  Ideally, we publish to npm `ts-mockito` if and when NagRock grants us access.  Until then, should we publish to:

* @cspotcode/ts-mockito
* @typestrong/ts-mockito
* @ts-mockito/ts-mockito

I am still waiting to hear from npm support about the @typestrong scope.  I am also not sure if organizations have granular permissions.  We would want to be sure ts-mockito maintainers have access to publish @typestrong/ts-mockito, but *not* to publish unrelated typestrong packages with different maintainership teams.

I have successfully reserved the `@ts-mockito` scope.

**Comment by LironHazan** [comment]
so if it won't be easy/possible to publish into @typestrong/ts-mockito we can go with @ts-mockito/ts-mockito IMO @cspotcode

**Comment by cspotcode** [comment]
I did some more googling and finally found what I was looking for.
https://docs.npmjs.com/managing-team-access-to-organization-packages
npm will let us create multiple teams inside an organization, each with access to their own packages.  So we can use `@typestrong/ts-mockito` if/when npm support replies to me.  I'll wait a bit longer for them to reply.

**Comment by cspotcode** [comment]
I would avoid making any changes that are likely to cause merge conflicts
with code or pull requests already written for either of the other 2
ts-mockito repositories.  Better to be able to cleanly merge pre-existing
features and bugfixes.

Why is your npm username?  I'll add it to the organization.

**Comment by cspotcode** [comment]
How do you want to handle changelogs?

I don't have a strong opinion.  For ts-node we use Github Releases, ([example](https://github.com/TypeStrong/ts-node/releases/tag/v10.2.0)) and I've recently started adding issues and pull requests to "milestones" to help me create the release notes.

**Comment by cspotcode** [comment]
Let's use Github Releases since NagRock already does: https://github.com/NagRock/ts-mockito/releases

The big things that I *personally* try to avoid are:

- automatically generating changelogs from commit logs.  This requires commit logs to be too perfect.  Commits can get messy; sometimes multiple PRs implement a single feature. Better to write a changelog by hand after a release is completed, IMO
- Immutable changelogs.  I don't publish the changelog to npm inside the package.  If we make a mistake, we should be able to fix it.

Both Github Releases and CHANGELOG.md let us make corrections and amendments to the changelog at any time, which is a good thing.

**Comment by LironHazan** [comment]
12 is great I see there're conflicts, I'll review when possible

**Comment by cspotcode** [comment]
It took a little while, but npm transferred the @typestrong scope to me.  I'm on vacation this weekend, but I can publish an initial release of @typestrong/ts-mockito when I'm back.

**Comment by pauleustice** [comment]
@cspotcode Do you have still plan to release this to npm? Or is there another way I can consume it? The original ts-mockito stopped working with Angular 14 and I'd like to see if your fork resolves the issue at all.

FYI the issue seems to be that `const serviceSpy = spy(someAngularService)` (when someAngularService is the service being tested, and not a dependency) replaces the service entirely with a mock implementation. This obviously breaks all the tests.

It used to retain the service as is, but allow us to mock specific method calls e.g.

`when(serviceSpy.someFunction(anything(), anything())).thenReturn(foo);`

**Comment by LironHazan** [comment]
@pauleustice 
Hey I replied on the other thread that our tests which use tsmockito works fine but we're actually not using TestBed, and since we're running with Jest we're also using the jest.spyOn method:

Here's an example of instantiation without the TestBed, the mocked instances are directly injected,
```TS
describe(' test query editor', () => {
  let component: QueryEditorComponent;
  const mockedFeaturesFlagService = mock(FeatureFlagsService);
  const mockedS1qlLangService = mock(S1qlLangService);
  const mockedPQLLangService = mock(PowerQueryLangService);
  const mockedQueryEditorService = mock(QueryEditorService);
  const mockedCdr = mock(ChangeDetectorRef);

  beforeEach(() => {
    component = new QueryEditorComponent(
      instance(mockedS1qlLangService),
      instance(mockedPQLLangService),
      instance(mockedQueryEditorService),
      instance(mockedFeaturesFlagService),
      instance(mockedCdr)
    );
  });
  
    it('should emit validation state when invoking updateValidationState', () => {
    jest.spyOn(component.validationState, 'emit');
    component.updateValidationState(true);
    expect(component.validationState.emit).toHaveBeenCalledTimes(1);
    expect(component.validationState.emit).toHaveBeenCalledWith({ isValid: true });
  });
  ```
  
I guess @cspotcode didn't publish to npm yet

**Comment by pauleustice** [comment]
@LironHazan Thanks for both your replies :) I looked at replacing the ts-mockito `spy()` with jest's `spyOn` (we're also using Jest), and while it worked, there were 2 problems:

- We have thousands of tests, so it's not an option right now
- It doesn't offer a combination of `toHaveBeenCalledTimes` and `toHaveBeenCalledWith`, which you get with ts-mockito
  - This would mean a reduction in our test quality

e.g. ` verify(serviceSpy.someMethod('foo')).times(3);`

It's a small distinction, but something we use a lot in our test suites.

**Comment by LironHazan** [comment]
@pauleustice I see..
As a workaround you can:
1. Write an eslint rule which will transform the specs to replace the single verify().times with the Jest alternative, but it means loosing the check of calling the fn with specific param x times..
2. Use [patch-package](https://www.npmjs.com/package/patch-package) to patch a fix on the original ts-mockito and you'll have a local fix 

If you'll have a working local fix you can open a PR to this repo and I'll merge it,
I don't think @cspotcode published @typestrong/ts-mockito to npm yet,
@cspotcode can you publish?
Meanwhile I can upgrade the typescript version

**Comment by cspotcode** [comment]
Yeah, I can publish this weekend.  Is the current state of the code good for publication, and what should the version number be?

**Comment by LironHazan** [comment]
@cspotcode I see we're 8 commit behind, I'll try to update this PR --> https://github.com/TypeStrong/ts-mockito/pull/12 first,
version 2.6.1?

**Comment by pauleustice** [comment]
Thanks both. Yep, a schematic of some sort to transform the occurrences is probably the next bet. Thanks for the heads up on patch-package, hadn't heard of that before. Unfortunately I'm not familiar enough with ts-mockito yet to understand the problem.

I did create this [test repo](https://github.com/pauleustice/ts-mockito-bug-ts) which demonstrates the problem though. It occurs with TS >4.3.5.

If you're able to publish this fork as a package I will see if it solves the issue :)

**Comment by LironHazan** [comment]
@pauleustice Unfortunately the typescript upgrade didn't help, I just tested locally with your repo :/

```
 FAIL   mockito-test  apps/mockito-test/src/app/example.service.spec.ts
  ExampleService
    spying and mocking on service under test
      ✓ should spy on ExampleService methods (20 ms)
      ✓ should return mocked value (5 ms)
      ✓ should not mock spied service observable - marbles (4 ms)
      ✓ should not mock spied service observable - subscribe (2 ms)
    mocking observables on providers
      first provider
        ✓ should mock out observable - marbles (2 ms)
        ✓ should mock out observable - subscribe (6 ms)
      second provider
        ✓ should mock out observable - marbles (2 ms)
        ✓ should mock out observable - subscribe (2 ms)
    mocking combineLatest observables on service under test
      ✓ should not mock out rxjs combineLatest (2 ms)
      ✕ should mock out providers with combineLatest - subscribe (3 ms)
      ✕ should not mock for local observables in combineLatest - subscribe (2 ms)
      ✕ should not mock for local observables in combineLatest with no pipe (16 ms)

  ● ExampleService › mocking combineLatest observables on service under test › should mock out providers with combineLatest - subscribe

    TypeError: service.combinedProviderObservable$.subscribe is not a function

      159 |       // The providers have mock values set in beforeEach, so the combinedProviderObservable$
      160 |       // should return those values
    > 161 |       service.combinedProviderObservable$.subscribe(value => {
          |                                           ^
      162 |         expect(value).toEqual('mockedProviderOneObservable/mockedProviderTwoObservable');
      163 |         done();
      164 |       });

      at src/app/example.service.spec.ts:161:43
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:409:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3830:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:408:56)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:169:47)
      at Object.wrappedFunc (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4331:34)

  ● ExampleService › mocking combineLatest observables on service under test › should not mock for local observables in combineLatest - subscribe

    TypeError: service.localCombinedObservable$.subscribe is not a function

      170 |
      171 |       // See 'should not mock spied service observable - subscribe', which passes
    > 172 |       service.localCombinedObservable$.subscribe(value => {
          |                                        ^
      173 |         expect(value).toEqual('realObservableOne/realObservableTwo');
      174 |         done();
      175 |       });

      at src/app/example.service.spec.ts:172:40
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:409:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3830:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:408:56)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:169:47)
      at Object.wrappedFunc (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4331:34)

  ● ExampleService › mocking combineLatest observables on service under test › should not mock for local observables in combineLatest with no pipe

    TypeError: actual.subscribe is not a function

      180 |       // or the pipe(map())
      181 |
    > 182 |       expect(service.localCombinedObservableNoPipe$).toBeObservable(
          |                                                      ^
      183 |         hot('a', {
      184 |           a: [ 'realObservableOne', 'realObservableTwo' ],
      185 |         }),

      at VirtualAction.<anonymous> (../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:431:31)
      at VirtualAction.Object.<anonymous>.AsyncAction._execute (../../node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:122:12)
      at VirtualAction.Object.<anonymous>.VirtualAction._execute (../../node_modules/rxjs/src/internal/scheduler/VirtualTimeScheduler.ts:89:28)
      at VirtualAction.Object.<anonymous>.AsyncAction.execute (../../node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:97:24)
      at TestScheduler.Object.<anonymous>.VirtualTimeScheduler.flush (../../node_modules/rxjs/src/internal/scheduler/VirtualTimeScheduler.ts:32:26)
      at TestScheduler.Object.<anonymous>.TestScheduler.flush (../../node_modules/rxjs/src/internal/testing/TestScheduler.ts:155:16)
      at Object.toBeObservableComparer (../../node_modules/jasmine-marbles/bundles/jasmine-marbles.umd.js:453:15)
      at __EXTERNAL_MATCHER_TRAP__ (../../node_modules/expect/build/index.js:386:30)
      at Object.throwingMatcher [as toBeObservable] (../../node_modules/expect/build/index.js:387:15)
      at src/app/example.service.spec.ts:182:54
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:409:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3830:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:408:56)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:169:47)
      at Object.wrappedFunc (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4331:34)


=============================== Coverage summary ===============================
Statements   : 85.29% ( 29/34 )
Branches     : 75% ( 6/8 )
Functions    : 40% ( 2/5 )
Lines        : 81.48% ( 22/27 )
================================================================================
Test Suites: 1 failed, 1 total
Tests:       3 failed, 9 passed, 12 total
Snapshots:   0 total
Time:        1.776 s
Ran all test suites.
```

The stacktrace won't imply of any ts-mockito source, can we isolate the Angular related abstractions (zone and jasmine wrappers) and make a simple typescript test with a combineLatest?

**Comment by pauleustice** [comment]
@LironHazan I've just pushed that to master on the test repo; basically removed TestBed, and changed the Angular service to a basic class. The tests still error.

Should I create a separate issue for this, since it seems we've established that there is an issue?

**Comment by pauleustice** [comment]
@LironHazan Oops, my bad. I forgot to remove the `Injectable()` bits from the Provider (juggling a lot of stuff today!)

I'm having a look now (by creating a blank Typescript-only project in the workspace), but currently getting lots of failures...

**Comment by LironHazan** [comment]
@pauleustice Now I'm getting the jest runner (jest-circus) trace and still no mention to lead to the ts-mockito source,
I tested in front of the upgraded ts-mockito source (ts version 4.4.7) while the host project ts version was 4.4.3 and it failed, but when I downgraded the version of the hosted project to 4.3.5 like you mentioned - the tests passed,
So we should look for the difference between the transpiled **test file** javascript of 4.3.x and 4.4.x, WDYT?

**Comment by pauleustice** [comment]
@LironHazan You wouldn't expect to see ts-mockito in the stack trace though, would you? (Since it isn't that that's erroring). It's just mocking class fields that it shouldn't (I believe) when running `spy()` which then cause the errors. However, what makes very little sense to me is why Typescript in **the project** would affect how `ts-mockito` behaves.

Do you want to raise a PR against my test repo and I can have a look when I get a chance? I have to leave my computer now unfortunately but will continue later on this evening or tomorrow morning.

**Comment by LironHazan** [comment]
@pauleustice I wouldn't expect to see ts-mockito errors but I wanted to be sure that it's not,
umm why do you think it mocks fields that shouldn't?

Thinking out load:
With TS 4.4.x following line fails: 
`service.combinedProviderObservable$.subscribe((value)`

TypeError: service.combinedProviderObservable$.subscribe is not a function


I've printed the service for 4.4.x and got:       
`'**combinedProviderObservable$**': [Function (anonymous)],
`

And for 4.3.x  we get:
```
     'combinedProviderObservable$': Observable {
        _isScalar: false,
        source: Observable {
          _isScalar: false,
          source: [Observable],
          operator: [CombineLatestOperator]
        },
        operator: MapOperator { project: [Function (anonymous)], thisArg: undefined }
      }
```

When removing the use of spy it works in 4.4.x,
In TS 4.4.x: When using spy CombineLatest returns a function ref and without the spy the CombineLatest returns an observable.
Won't happen in TS 4.3.x
Wow I don't have a clue, 
I'm unfamiliar as well with the spy related code, but what I can do in this repo is adding the test with rxjs that would fail and then we can debug on ts-mockito source.

I'll open a dedicated issue

**Comment by cspotcode** [comment]
Published to npm, as @typestrong/ts-mockito v2.6.2, because upstream ts-mockito had already published a 2.6.1, so that git tag was already taken.

https://www.npmjs.com/package/@typestrong/ts-mockito

@LironHazan has also been given access to publish new versions.
